### PR TITLE
Tweak find command functionality based on modes

### LINKED ISSUE #192: Find Command Not Working As Expected
Current Behaviour 
Find command filters the cards displayed regardless if deck is selected or not.

Expected Behaviour
When deck is not selected, find command filters deck
When deck is selected, find command filters cards within the selected deck

### PR DESCRIPTION
**Pull request by ruiyigan**
Closes #192 

When deck is not selected, find command filters the deck section
When deck is selected, find command filters the card section

https://user-images.githubusercontent.com/85063215/227448272-c02a29e3-2cb9-4207-a986-ee5211e3367e.mov

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -19,24 +25,49 @@ public class FindCommand extends Command {
...
-    public CommandResult execute(Model model) {
+    public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
-        model.updateFilteredCardList(predicate);
+        String returnMessage;
+        int returnListSize;
+        ModelState currentState = model.getState();
+        switch (currentState) {
+        case DECK_MODE:
+            model.updateFilteredCardList(cardPredicate);
```
Comment (rockman007372) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:49]: Interesting behaviour, but I wonder if its confusing or counterintuitive for user - What if they are in deck mode and they want to filter the decks too?

**Review by rockman007372 — APPROVED** [review]
LGTM except a minor concern!

File: src/main/java/seedu/address/logic/commands/FindCommand.java (hunk 1 above)
Comment (ruiyigan) [reply src/main/java/seedu/address/logic/commands/FindCommand.java:49]: hmm but deck mode means you have a deck selected right. I think it makes sense to be filtering for cards after a deck is selected?

Comment (rockman007372) [reply src/main/java/seedu/address/logic/commands/FindCommand.java:49]: I thought so because right now we allow users to select a deck from Deck mode too. Actually whats the point of showing the cards in the main mode anyway ahh, its not like we can interact with them right?

Comment (ruiyigan) [reply src/main/java/seedu/address/logic/commands/FindCommand.java:49]: We are currently displaying all cards when in main mode if I'm not wrong. I agree. I think we shouldn't show all cards in the main mode as we may confuse the user as to which mode they are in.
