### PR TITLE
Test cases for Deck Command Parser

### LINKED ISSUE #142: [Bug] Wrong error messages for deck commands
Screenshot 2023-03-19 at 15 29 09

Screenshot 2023-03-19 at 15 53 00

### PR DESCRIPTION
**Pull request by ruiyigan**
Closes #142 #144

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -98,7 +98,7 @@ public static Deck parseDeck(String deckName) throws ParseException {
         requireNonNull(deckName);
         String trimmedDeckName = deckName.trim();
         if (!Answer.isValidAnswer(trimmedDeckName)) {
```
Comment (rockman007372) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:100]: we should create a DeckName class soon. Right now we are still checking validAnswer on deck names...

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 2]
```diff
@@ -30,18 +30,20 @@ public class CommandTestUtil {
...
-    public static final String NAME_DESC_AMY = " " + PREFIX_QUESTION + VALID_QUESTION_GRAVITY;
-    public static final String NAME_DESC_BOB = " " + PREFIX_QUESTION + VALID_QUESTION_PHOTOSYNTHESIS;
-    public static final String ADDRESS_DESC_AMY = " " + PREFIX_ANSWER + VALID_ANSWER_GRAVITY;
-    public static final String ADDRESS_DESC_BOB = " " + PREFIX_ANSWER + VALID_ANSWER_PHOTOSYNTHESIS;
-    public static final String TAG_DESC_FRIEND = " " + PREFIX_TAG + VALID_TAG_MEDIUM;
-    public static final String TAG_DESC_HUSBAND = " " + PREFIX_TAG + VALID_TAG_HARD;
-
-    public static final String INVALID_NAME_DESC = " " + PREFIX_QUESTION; // empty string not allowed for question
-    public static final String INVALID_ADDRESS_DESC = " " + PREFIX_ANSWER; // empty string not allowed for addresses
+    public static final String QUESTION_DESC_GRAVITY = " " + PREFIX_QUESTION + VALID_QUESTION_GRAVITY;
```
Comment (rockman007372) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java:35]: Thanks for the thorough refractoring!

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java [hunk 3]
```diff
@@ -64,25 +80,12 @@ public void parse_compulsoryFieldMissing_failure() {
...
     public void parse_invalidValue_failure() {
-        // invalid name
-        //        assertParseFailure(parser, INVALID_NAME_DESC + ADDRESS_DESC_BOB
-        //                + TAG_DESC_HUSBAND + TAG_DESC_FRIEND, Question.MESSAGE_CONSTRAINTS);
-        //
-        //        // invalid address
-        //        assertParseFailure(parser, NAME_DESC_BOB + INVALID_ADDRESS_DESC
-        //                + TAG_DESC_HUSBAND + TAG_DESC_FRIEND, Answer.MESSAGE_CONSTRAINTS);
-        //
-        //        // invalid tag
```
Comment (rockman007372) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:75]: We can make use of the InvalidTag test case?

File: src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java [hunk 4]
```diff
@@ -18,6 +18,7 @@ public static void assertParseSuccess(Parser<? extends Command> parser, String u
             Command expectedCommand) {
         try {
             Command command = parser.parse(userInput);
+            System.out.println(userInput);
```
Comment (rockman007372) [inline src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java:21]: Oh can we leave println statement here?

File: src/test/java/seedu/address/logic/parser/EditCommandParserTest.java [hunk 5]
```diff
@@ -146,25 +144,6 @@ public void parse_multipleRepeatedFields_acceptsLast() {
         assertParseSuccess(parser, userInput, expectedCommand);
     }
 
-    /*
-    @Test
-    public void parse_invalidValueFollowedByValidValue_success() {
```
Comment (rockman007372) [inline src/test/java/seedu/address/logic/parser/EditCommandParserTest.java:151]: Hmm im not sure what this test does... Is it irrelevant to our Edit behaviour?

**Review by rockman007372 — APPROVED** [review]
LGTM but I have a few questions regarding some test cases!

File: src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java [hunk 6]
```diff
@@ -30,7 +29,7 @@ public EditDeckCommand parse(String args) throws ParseException {
             index = ParserUtil.parseIndex(i);
```
Comment (rockman007372) [inline src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java:29]: We definitely need to find a different way to parse string.  `args.charAt(1)` will not work if the index has 2 digits eg. 11, because the index parsed will become 1 and not 11!

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 1 above)
Comment (unfazing) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java:100]: #148

File: src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java [hunk 7]
```diff
@@ -21,7 +20,7 @@ public class EditDeckCommandParser implements Parser<EditDeckCommand> {
      */
     public EditDeckCommand parse(String args) throws ParseException {
         requireNonNull(args);
-        ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args);
+        ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args); // are we using this?
```
[the remark this answers is not in the document]
Comment (rockman007372) [reply src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java:23]: Already address this in #149
